### ISSUE TITLE
Implement Starknet pallet hooks

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/kaioshin#25]
# Description

Implement the required substrate pallet hooks for `Starknet` pallet.

The list of possible hooks are defined [here](https://paritytech.github.io/substrate/master/frame_support/traits/trait.Hooks.html).

We need to identify which ones we have to implement.

**Comment by a-moreira** [comment]
@abdelhamidbakhta what exactly are the automatic functionalities we need to provide? 
I can see [here](https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/transaction-life-cycle/#the_pending_block) in the docs I can see this status of the block as an example, although it says it will be deprecated.

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta what exactly are the automatic functionalities we need to provide? I can see [here](https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/transaction-life-cycle/#the_pending_block) in the docs I can see this status of the block as an example, although it says it will be deprecated.

It's not clear for the moment. I don't consider this issue as ready to be started yet.
Do you want to work on something else ? I can create more issues
